version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/arquichat
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 600
      runas: ubuntu
  AfterInstall:
    - location: scripts/install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 600
      runas: ubuntu
#   ApplicationStop:
#     - location: stop_server.sh
#       timeout: 600
#       runas: ubuntu

#   BeforeInstall:
#     - location: install_dependencies.sh
#       timeout: 600
#       runas: ubuntu