version: 0.0
os: linux

files:
  - source: scripts
    destination: /home/ubuntu/arquichat
permissions:
  - object: scripts
    pattern: "**"
    owner: ubuntu
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 600
      runas: ubuntu
  AfterInstall:
    - location: install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: start.sh
      timeout: 600
      runas: ubuntu
#   ApplicationStop:
#     - location: stop_server.sh
#       timeout: 600
#       runas: ubuntu

#   BeforeInstall:
#     - location: install_dependencies.sh
#       timeout: 600
#       runas: ubuntu