version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/arquichat
permissions:
  - object: /opt/codedeploy-agent/deployment-root/c42ae13b-441d-4af1-a910-cb1b4687bb31/d-NON2BJ686/deployment-archive/scripts/
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 600
      runas: ubuntu
  AfterInstall:
    - location: scripts/install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 600
      runas: ubuntu
#   ApplicationStop:
#     - location: stop_server.sh
#       timeout: 600
#       runas: ubuntu

#   BeforeInstall:
#     - location: install_dependencies.sh
#       timeout: 600
#       runas: ubuntu