# Generated by Django 2.2.16 on 2020-09-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
